### ISSUE TITLE
revolt status icons

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [lo-kiss/revolt-tweaks#1]
is there a way to change the shapes of the status icons to make them use the discord status icon shapes

**Comment by lo2dev** [comment]
Unfortunately, the status icon doesn't have an identifier that changes based on the status therefore I can't do it with CSS. Your best bet would be if this is implemented in the client itself.

**Comment by pinkjimrussiagirl** [comment]
> Unfortunately, the status icon doesn't have an identifier that changes based on the status therefore I can't do it with CSS. Your best bet would be if this is implemented in the client itself.

idk where i can do that, and i can’t edit the source code because some people might not be happy with that and change it back

here’s what the shapes look like that i’m trying to add
![image](https://github.com/lo-kiss/revolt-css-snippets/assets/111091825/5f59fba9-47c6-407f-9fdf-50126011613e)


note: when i click the status icons in inspect element it comes up as an element like <circle> which is part of a css, but if i look for the css it shows the pfp itself (note: i am a beginner and very bad at any type of coding)

i also need help with the image radius because only a few have rounded edges on all corners and the rest only does it on the left side

**Comment by lo2dev** [comment]
Not every change has to go upstream necessarily, so you could fork the client, make the changes, keep them local and use the client locally.

**Comment by lo2dev** [comment]
> i also need help with the image radius because only a few have rounded edges on all corners and the rest only does it on the left side

Please, file another issue if you want help with something else CSS related.

**Comment by pinkjimrussiagirl** [comment]
> Not every change has to go upstream necessarily, so you could fork the client, make the changes, keep them local and use the client locally.

idk how i can do that because i also want to see the changes on mobile as well without having to spend a lot of money just to get a site running

i’m also thinking of making my own chat place, but idk where to start and also i’m very bad ad coding

**Comment by lo2dev** [comment]
You don't need to buy a website to have a working client locally. Though, like you said you don't have coding experience so you either learn or just wait until someone implements the things you want or if they don't you accept it and move on. Also if your main device is a phone then it'll be a little trickier than on a desktop.

**Comment by pinkjimrussiagirl** [comment]
> You don't need to buy a website to have a working client locally. Though, like you said you don't have coding experience so you either learn or just wait until someone implements the things you want or if they don't you accept it and move on. Also if your main device is a phone then it'll be a little trickier than on a desktop.

i use both phone and computer but if i was to make a local client that would mean i would have to have my computer running 24/7 otherwise the local client site wouldn’t load

**Comment by lo2dev** [comment]
Well that's something you'd have to figure out on your own.

**Comment by lo2dev** [comment]
I'm closing this as not planned because it's not doable with pure CSS as far as I know.

**Comment by pinkjimrussiagirl** [comment]
> I'm closing this as not planned because it's not doable with pure CSS as far as I know.

ok, so does that mean i have to use javascript to be able to change the shapes

**Comment by lo2dev** [comment]
Probably, but that's outside the scope of this issue and repository. I'm going to have to ask you to stop replying to this issue.

**Comment by pinkjimrussiagirl** [comment]
> Probably, but that's outside the scope of this issue and repository. I'm going to have to ask you to stop replying to this issue.

ok i will stop replying
