### ISSUE TITLE
help with status bar

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [lo-kiss/revolt-tweaks#2]
is there a way to make the ios and android status bar transparent just by using css so i can make background images or gradients appear in it since i don’t want to risk ruining revolt by messing with the source code

**Comment by lo2dev** [comment]
It's not possible with pure css, especially when the css is only applied to the app itself and doesn't reach the outside.

**Comment by pinkjimrussiagirl** [comment]
> It's not possible with pure css, especially when the css is only applied to the app itself and doesn't reach the outside.

so does that mean i can only do it with javascript

**Comment by pinkjimrussiagirl** [comment]
also is there a way that i can make my own chat place even though i am a beginner at coding, because i’m trying to find a chat app that is purely made in the uk and doesn’t have mean people in support but i cannot find any chat apps made in uk because 90% of stuff internet related is made in usa (in or near the california area)

sorry if this is off topic, i just needed help with if it’s possible for me to make my own chat app

note: my own chat app will not be open source, meaning the only person updating it will be me and possibly some of my friends

**Comment by lo2dev** [comment]
If you plan on using revolt source code for your own chat place then you can't make it closed source because of the LICENSE. If you wanna make it closed source you gotta do it from scratch. There are plenty of tutorials out there.

**Comment by lo2dev** [comment]
Please stop going off topic in issues and replying after the issue was closed.

**Comment by pinkjimrussiagirl** [comment]
> Please stop going off topic in issues and replying after the issue was closed.

ok i will stop, also i won’t be using the revolt source code in my own chat place because it would count as copying even if it is open source (i will need help with starting my own chat place and then the rest i’ll try to do myself)

also the license on my own chat place will make it where no one is allowed to make any copies at all

also my own chat place won’t be made on github because people can fork it to make copies and even download the source code

sadly i cannot find any tutorials at all on how to make one

note: i am a beginner at coding which is why i will need help with starting it off

**Comment by lo2dev** [comment]
You don't seem to get the point so I'm going to lock the issue.
